### ISSUE TITLE
Q: question about the security context of the file mount point after the tmpfs file system is mounted?

### ISSUE THREAD

**Issue by linux-gcc** [SELinuxProject/selinux-notebook#25]
On CentOS 8.4 systems encountering a mount point security context for a tmpfs file becomes system_u:object_r:adjtime_t:s0, this issue is epidoxical. What is the usual cause of this problem?

**Comment by WOnder93** [comment]
This might be the kernel bug fixed by this commit: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=cbfcd13be5cb2a07868afe67520ed181956579a7

It should be fully fixed in RHEL/CentOS 8.7+. Can you try upgrading?

(Also please don't report CentOS issues here. There is [Red Hat Bugzilla](https://bugzilla.redhat.com/) for that.)

**Comment by pcmoore** [comment]
I believe @WOnder93 already pointed you in the right direction @linux-gcc so I'm going to close this issue; please follow up on the Red Hat Bugzilla for Red Hat specific issues, thank you.
